### ISSUE TITLE
Version Update

### ISSUE THREAD

**Issue by MDKAOD** [creecros/AutoSubtasks#12]
Please revise AutoSubtasks version so Kanboard's plugin directory allows updating of the plugin. Thank you!

**Comment by creecros** [comment]
Didn't even realize that's how updates worked I was just being lazy and didn't want to do a pull request to update the version. I'll make a new release and make a pull request on kanboard website next chance I get.

**Comment by creecros** [comment]
Should be all set

**Comment by MDKAOD** [comment]
Can we add

`
  public function getCompatibleVersion()
  {
    return '>=1.0.46';
  }
`
to the end?

I'm still too new to git to know how to pull the repository and push the change back to you. I'm trying to address https://github.com/kanboard/kanboard/issues/3873

**Comment by creecros** [comment]
It's 1.0.48 or greater

**Comment by creecros** [comment]
updated plugins.json and plugins.php to 1.0.48 or greater, updated release file.

**Comment by MDKAOD** [comment]
I almost wonder if there's a whitelist, because in the documentation I saw a reference to hosted solutions having an auto update. Kanboard lead Dev really should weigh in on the ticket. Thanks for your time on this.

**Comment by creecros** [comment]
There's something going on, just not sure what. I'll look into it when I actually get a moment, now that I understand what your trying to accomplish

**Comment by creecros** [comment]
Ah, I think I know what the issue is. I'll test once I get the wife and kids to leave me alone.

**Comment by creecros** [comment]
solved it.

`title` in plugins.json has to match `name` in Plugins.php
