### ISSUE TITLE
SQL Error: invalid input syntax for integer: ""

### ISSUE THREAD

**Issue by eugene-taylashev** [creecros/AutoSubtasks#16]
Dear Craig,
I use Kanboard v1.2.8 with 'Auto Subtask Creation' and SubtaskDueDate plugins installed and PgSQL 9.6.11 as a backend.
I created an Automatic Action for a project with the following parameters:

Create one or more Subtasks Automatically based on a category
Event name = Task creation or modification
Category = Bug
Assignee = Unassigned
Subtask Title(s) = Subtask 1 Subtask 2 Subtask 3
Estimated Time in Hours =
Duration in days =

Please note that 'Estimated Time in Hours' and 'Duration in days' are empty

I am getting the SQL Error below when I've created a new task with the category "Bug":
**Internal Error: SQL Error: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: ""**

But if 'Estimated Time in Hours' and 'Duration in days' are specified, **there is no such error**. 
Looks like an empty string parameter is not turned to int 0 or NULL before executing the sql query.

Regards
Eugene

P.S. Thanks a lot for the plugin ;-)

**Comment by eugene-taylashev** [comment]
### More info... 
Performed test cases for the same parameters, except 'Estimated Time in Hours' and 'Duration in days'.
Here are results:
Estimated Time in Hours = "", Duration in days = ""  => Error, no sub-tasks
Estimated Time in Hours = 8, Duration in days = ""  => No error, no sub-tasks
Estimated Time in Hours = "", Duration in days = 7  => Sub-tasks created
Estimated Time in Hours = 8, Duration in days = 7 => Sub-tasks created

**Comment by creecros** [comment]
i'd say that adding 
```php
$duration = $this->getParam('duration');
if (!isset($duration)) { $duration = 0; }
```

and replacing
```php
      'due_date' => strtotime('+'.$this->getParam('duration').'days'),
```

with
```php
      'due_date' => strtotime('+'.$duration.'days'),
```

in both non vanilla actions, would solve.

You got this? or do i need to do it?

**Comment by creecros** [comment]
or would it be `!empty()`...one of the two.

**Comment by creecros** [comment]
although, ironically, i decided to test and, I don't get this error. I've tested in 

kanboard 1.2.8, with sqlite...
kanboard 1.2.8, with mysql 5.7...
kanboard 1.2.6 with pgdg90+1

**Comment by creecros** [comment]
and just for added testing i did, kanboard 1.2.8 with pgdg90+1, just to make sure.
