### ISSUE TITLE
"Create" vs "Add" terminology leading to confusion?

### ISSUE THREAD

**Issue by nekohayo** [creecros/AutoSubtasks#17]
Having enabled the plugin, I saw it added automatic actions for:
* Create one or more Subtasks Automatically based on column
* Create one or more Subtasks Automatically based on category

(note: I doubt Subtasks and Automatically would need to have capitalized letters in those sentences)

...but I also saw, at the top of the choices, "_Add_ a subtask and activate the timer when moving a task to another column". That got me puzzled, as it sounds very similar to one of the two options above. Is there a difference between Add and Create? Or is the "Add" one built-in with Kanban mainline/core and there is some overlap with the feature you present here? Just filing the issue here to let you know that I find it a little bit confusing, maybe there's a way to make it clearer what is what, or to unify the terminology :)

**Comment by creecros** [comment]
It's a language barrier. Whoever wrote that one is definitely french.

**Comment by creecros** [comment]
But, if we are getting technical...
If there is an apple on the table, and I place another one on the table to sit next to previous apple, I have added an apple. If I don't have an apple to add to the table, I would have to "create" an apple to add it. Create, would be the appropriate terminology. 

Automatically wouldn't need to be capitalized, but, I am a who I am, and I spell, write, code, banter, the way I do, and it presents itself here.

**Comment by creecros** [comment]
Some insight to this dilemma:

https://github.com/kanboard/kanboard/blob/0d8fbc85d8c0c4dc718c44b93381dab28ed348a7/app/Action/SubtaskTimerMoveTaskColumn.php#L9

Also, That action was released with v1.1.1 and not added until around December of 2017. 

My actions were originally created Sept of 2017.

They are slightly different, as that one provided in the Core
- New automatic action to create a subtask assigned to the creator and start the timer (Notice the use of "Create")

And mine, allows you to create subtasks and assign to whoever you want, without starting the timer.
Mildly different.

Why the person who wrote that, would choose to label it in the list of actions with "Add" and title it everywhere else with "Create" is beyond me.
