### ISSUE TITLE
Feature Request - Default Action to replicate Task title to Subtask

### ISSUE THREAD

**Issue by eskaryo** [creecros/AutoSubtasks#2]
Auto parameters allow for the Subtasks to be created with a Static name, it would be preferential to allow the user to replicate the name of the Task to the Subtask

**Comment by creecros** [comment]
That one shouldn’t be to hard...if get time.

**Comment by creecros** [comment]
updated, haven't tested. simply leave subtask title blank and it "should" use the task title...going on memory of variables...could have been wrong. I'll test eventually.
