### ISSUE TITLE
Cannot edit subtask list after creation

### ISSUE THREAD

**Issue by davidrea** [creecros/AutoSubtasks#22]
After setting up a new "Create one or more Subtasks Automatically based on column" automatic action in a project, the list of subtasks is fixed. The only option under the action's "gear" menu is "Remove".

For longer lists of subtasks, removing and re-creating the list when adding or removing a subtask can get tedious. It's possible to do by copy-and-paste (**if** you remember to copy the list before deleting the old action) but you then have to break up the pasted list into separate lines.

**Comment by creecros** [comment]
"Remove" is the only option available for all automatic actions, thats not a result of the plugin, but kanboard.

**Comment by davidrea** [comment]
Ahh, thanks...I thought I'd seen an edit option for other ones, but looking back I clearly hadn't! Sorry for the inbox noise...
