### ISSUE TITLE
Feature Request - 'Apply to all columns' when creating action

### ISSUE THREAD

**Issue by eskaryo** [creecros/AutoSubtasks#3]
This feature would save a lot of time creating the actions

**Comment by creecros** [comment]
Think this doable as well...again if I get the time.

**Comment by creecros** [comment]
looks like a few solutions...

1.) edit the form Template/action_creation/params.php to include a default checkbox callout based on t(), not by any means am i a expert in php though, and would require editing extra code outside plugin.
2.) add a field where user can type "yes", or "all" or something similar, but it would still ask for a column before it got there.
3.) separate this feature and simply create an additional action that applies to all columns. easiest option.

**Comment by creecros** [comment]
Think I figured this out... stay tuned.

**Comment by creecros** [comment]
Feature added
