### ISSUE TITLE
Feature Request - Option to not auto create Subtask for Tasks which already have Subtasks

### ISSUE THREAD

**Issue by eskaryo** [creecros/AutoSubtasks#6]
There should be a selectable mechanism for the plugin to skip Subtask creation if the incoming Task already contains Subtasks. EG: When a Task with Subtasks is duplicated.

**Comment by creecros** [comment]
Which already have subtask, or subtask of the same title?

**Comment by eskaryo** [comment]
Already have any subtask

**Comment by creecros** [comment]
same as #3, i should probably just figure this out, not sure how to present a check box. I can only think of adding a callout t() reference to params.php. need to look at some examples of how others edit form templates in a plugin.

**Comment by creecros** [comment]
This isn't something I would want, but maybe as a don't duplicate subtask would be something practical.

**Comment by dasBuero** [comment]
I just started using your plugin and it saves a lot of time. Great job, thank you!

But I'm also missing something like a duplication check, so if there are already subtasks created, the autocreation mechanism should check for duplicates before creating new subtasks. This is in particular practical if you move one task back an forth in the swimlane.

**Comment by creecros** [comment]
ya, been meaning to come back and do that. it's on my to do list.

**Comment by creecros** [comment]
done
