### ISSUE TITLE
When creating a task I get "Internal Error: SQL error"

### ISSUE THREAD

**Issue by theblaine** [creecros/AutoSubtasks#7]
When creating a task I get "Internal Error: SQL error". It creates the task, but does not add any sub tasks.

**Comment by creecros** [comment]
Really doesn't tell me much. Can you provide more info, i.e. what version kanboard are you using.

**Comment by creecros** [comment]
I haven't tested or even used that new version of kanboard as of yet. I'll spin up a test server next chance I get and see if it duplicates the error.

**Comment by creecros** [comment]
Your missing the requirement:
[](https://github.com/creecros/AutoSubtasks#requirements)

**Comment by theblaine** [comment]
WOW! I can't believe I missed that. That was the problem. Thank you very much! I love this plugin!

**Comment by creecros** [comment]
I always suspected it was requirement, you verified it. Now I know how to make it not a requirement, so...thank you!

**Comment by theblaine** [comment]
Awesome!! I'll grab the next update when it's out!
